#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
. $WM_PROJECT_DIR/bin/tools/RunFunctions            # Tutorial run functions
#------------------------------------------------------------------------------

# ./Allclean
./Allmesh
# ./map
# ./bolsigRun
# ./run
./runParallel
# reconstructPar -allRegions -latestTime

#------------------------------------------------------------------------------
