#!/bin/bash
cd "${0%/*}" || exit                                # Run from this directory
#------------------------------------------------------------------------------

echo ========================================
echo Compile captionFOAM libraries
echo ========================================

#------------------------------------------------------------------------------

wmake libso parabolicInlet
wmake libso appliedVoltage
wmake libso transportTools
wmake libso plasmaChemistry
wmake libso electronEnergy
wmake libso plasmaFvPatchFields

#------------------------------------------------------------------------------

echo ========================================
echo Done compiling captionFOAM libraries
echo ========================================

#------------------------------------------------------------------------------
